apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/adglad/nginx.git
    targetRevision: HEAD
    path: overlay/dev
    kustomize:
      version: v4.4.0
